services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - pgData:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
  node_app:
    container_name: ink_flow_api
    build: ./backend
    ports:
      - 1234:5000
    env_file:
      - ./backend/.env
    depends_on:
      - db
  next_app:
    container_name: ink_flow
    build: ./frontend
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - next_app
volumes:
  pgData:
  